### ISSUE TITLE
Ethernet wasn't working on latest 2.3.1 release

### ISSUE THREAD

**Issue by carelw** [zacmks/Hackintosh-Aero-15X#21]
I have the same Aero 15X V8 (also added 16Gb RAM) as specified in this repository. I recently decided to dual boot to MacOS (new to dual booting, but other coding experience which helped) on it and have been following the resources here. Thanks for repository by the way.

**Bug details**
I had an issue getting the Realtek Ethernet card working on the latest 2.3.1 release. It was seeing the MAC address of the network card, but just stayed inactive regardless of plugging in or out an RJ-45 cable. Ended up reverting the RealtekRTL8111.kext to the one in release 2.3.0 which seemed to fix the issue, not sure if I need to configure the Contents/Info.plist differently in the latest version. I am booting OpenCore (not Clover) version.

**OS Details**
- Catalina 10.15.6 (19G2021)

**Added note**
I have managed to get both my Bluetooth and Wifi working on the original Intel wireless network card using [itlwm](https://github.com/OpenIntelWireless/itlwm) and [IntelBluetooth](https://github.com/OpenIntelWireless/IntelBluetoothFirmware) which I can add a commit to the repository if it would assist anyone else running the original card.

**Comment by zacmks** [comment]
You are welcome @carelw!

Thank you for testing! Sorry, I wasn't able to test RealtekRTL8111, so yess it's possible that it wasn't working with latest release.
I will check this week what the problem could be (and revert the version if it's not possible to fix). For hte time being, the old version should work well.

Note: We have a similar situation with USBInjectAll, on which the latest version doesn't work, so I kept an older version.

In regards of itlwm and IntelBluetooth. Were you able to test them in a way that they exist with Brcm drivers?
I mean, in a way that both Intel and Brcm kext can coexist in the repo? (I can test the Broadcom drivers on my side, if you'd be able to test the intel drivers on your side).
The idea is to have all files on a single EFI/OC folder, so that it's easy for everyone to use the repository (we can just copy/paste it :D).

If so, it'd be a great addition to repo :))

**Comment by carelw** [comment]
Great thanks. Could be that I was missing something but perhaps check if you can get the latest Realtek .kext working.

As for the co-existing with BRCM, I haven't removed (or deleted) your Broadcom .kext files, I did however untick the 'enable' of all the BRCM related .kexts in the config.plist to avoid conflicts. I could try enable them and see if there is any issue, otherwise I guess one could simply just enable / disable the .kext files in the .config based on your installed wireless card. Let me do some tests in the week with everything enabled and get back on that one.

**Comment by zacmks** [comment]
That's great, and then I'll test them with all enabled on my side to check the compatibility with Broadcom drivers

**Comment by carelw** [comment]
I have tested on my side with all kexts enabled for both Intel and Broadcom and didn't seem to have any issues. Wifi and Bluetooth still works. Did confirm the kexts were actually loaded using kextstat in terminal.
