### ISSUE TITLE
[BUG] Strange OpenCanopy Behaviour

### ISSUE THREAD

**Issue by Malumen** [zacmks/Hackintosh-Aero-15X#26]
**Describe the bug**
At boot selector, OpenCanopy no longer takes mouse input or trackpad input. In addition, using keyboard arrow keys acts as if multiple keystrokes entered. Pressing right arrow moves selector all the way to the right, pressing left makes selector go all the way to the left, and pressing tab causes selector to spam between shutdown and restart options.

**To Reproduce**
Steps to reproduce the behaviour: update to latest 2.4.5 from 2.4.3

**Expected behavior**
Single keystrokes at OpenCanopy screen correspond to single inputs for OpenCanopy selector

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 -  Version 10.15.7

**Additional context**
New OpenCanopy version seems to be larger in size.
Also @zacmks why are you still using USBInjectAll? Just curious as I thought USBmap and Hackintool kext are better for proper injection and UIA is deprecated. (and system has an ELAN trackpad, should we move away from voodoo?)

**Comment by zacmks** [comment]
Thank you for the detailed info on your request @Malumen 

The keyboard issue was actually an issue with OpenCore 0.6.8 (present on release 2.4.5).
This should be fixed on release 2.4.6
In regards to the mouse and trackpad issue, I might need to investigate it yet (not sure if it was fixed on this release).


About USBInjectAll, at the time it was the best way to inject USB config. I might take a look on USBMap whenever I get some time.
Previous issues that I had with other USB inject techniques were that they used to generate kexts tied with the macOS version currently being used.
Meaning, although they seemed user-friendly and easier to use at first glance, the issue was that whenever you updated to a newer macOS version, you had to re-create a new kext. This doesn't happen with USBInjectAll.


Is your trackpad + multi-touch working without Voodoo?

**Comment by zacmks** [comment]
@Malumen, just tested OpenCanopy with external picker. Problems seem solved with release 2.4.6.

Also, in regards of USBMap.kext. Just checked the solution and generated kext. Not changing for now.
Reasons are as follow:
- It doesn't work on Mojave and older
- Generated kexts seem tied with SystemProductName.

This means that USBInjectAll has the pro of working with more systems, and we don't need to re-generate the kext if we try to test the OC config with other SystemProductName.

The downside of USBInjectAll is the manual config/port mapping, which I already did :)
Also, although RehadMan is not active on the scene anymore, Sniki is working on it:
https://github.com/Sniki/OS-X-USB-Inject-All

Please let me know if any new issues.
