### ISSUE TITLE
You should update the Readme file with Mojave checklist

### ISSUE THREAD

**Issue by Jnss98b** [zacmks/Hackintosh-Aero-15X#8]
Just to be clear, everything works well on Mojave like on High Sierra except the dGPU, right?

**Comment by zacmks** [comment]
Yes indeed @Jnss98b

**Comment by zacmks** [comment]
Last time that I checked tough. 

I used to have a separate directory with Mojave version structure, but I deleted it bc it was the same as High Sierra.
Since I don't have much time to update the files concurrently I deleted it (bc for every update [for project quality purposes], I do want to update the files)

**Comment by zacmks** [comment]
^ This is, the reason that I don't have a separate section for Mojave

If you could test for me and give some insights @Jnss98b (what's working/not working), I can update the README file for everyone

**Comment by Jnss98b** [comment]
Sure, give me a week or two while I ready up my machine for installing MacOS. Also, do you know a more recent version of the wireless card you mentioned on the README file (Broadcom BCM94352Z) that's also MacOS compatible?? That thing only supports Bluetooth 4.0 while I would appreciate Bluetooth 5.0 support

**Comment by zacmks** [comment]
Tested myself. Everything works on Mojave except Nvidia graphics, which depends on compatible Nvidia Web Drivers release

https://github.com/zacmks/Hackintosh-Aero-15X/commit/9ac2abb0db45010286a00fd398699871da0852f1
